---
builds:
  - id: sandbox
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: sandbox
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/repo-scm/sandbox/cmd.BuildTime={{.Date}} -X github.com/repo-scm/sandbox/cmd.CommitID={{.ShortCommit}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
